name: Release Version

on:
  push:
    tags:
      - 'v*'  # Por ejemplo: v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Necesario para crear el release y subir assets

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Build ATM package
    - name: Install dependencies (ATM)
      working-directory: atm
      run: npm install

    - name: Pack ATM
      working-directory: atm
      run: |
        npm pack
        mv *.tgz ../atm.tgz

    # Build PAYMENT package
    - name: Install dependencies (Payment)
      working-directory: payment
      run: npm install

    - name: Pack Payment
      working-directory: payment
      run: |
        npm pack
        mv *.tgz ../payment.tgz

    # Create GitHub Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          🎉 Versión publicada automáticamente desde GitHub Actions.
          - ATM: atm.tgz
          - PAYMENT: payment.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Attach .tgz files
    - name: Upload ATM and Payment packages to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          atm.tgz
          payment.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
